server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com    # eureka 服务器端的实例名称
  client:
    register-with-eureka: false  # false 标识不向注册公司注册自己
    fetch-registry: false  # false 标识自己及时注册中心，我的职责就是维护服务实例。并不需要检索服务
    service-url:
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 设置与eureka server交互的地址查询服务和注册服务
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#eureka:
#  server:
#     enable-self-preservation: false #禁用自我保护