server:
   port: 8002

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml        #mybatis配置文件所在路径
   type-aliases-package: com.tit.springcloud.entity          #所有Entity别名类所在包
   mapper-locations: mybatis/mapper/**/*.xml        #mapper映射文件

spring:
  application: 
    name: microservicecloud-dept
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource         #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver           #mysql驱动包
    dbcp2:
       min-idle: 5                                 #数据库连接池的最小
       initial-size: 5                             #初始化连接数
       max-total: 5                                #最大连接数
       max-wait-millis: 200                        #等待连接获取的最大超时时间
       
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/#,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002      # 修改微服务名称
    prefer-ip-address: true                      # 设置ip地址访问


info:
  app.name: microservicecloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

    